//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProject
{
    public partial class Personen
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
    }
}
