//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProject
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
        protected global::System.Web.UI.WebControls.HyperLink lnkPersonen;
        protected global::System.Web.UI.WebControls.HyperLink lnkLeveranciers;
        protected global::System.Web.UI.WebControls.HyperLink lnkArtikelen;
        protected global::System.Web.UI.WebControls.HyperLink lnkVoorraad;
        protected global::System.Web.UI.WebControls.HyperLink lnkLog;
        protected global::System.Web.UI.WebControls.HyperLink lnkAlarm;
        protected global::System.Web.UI.WebControls.HyperLink lnkBeheer;
    }
}
